/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    3213: typeof import('./src/components/3213.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    Getform: typeof import('./src/components/getform.vue')['default']
    GetQRcode: typeof import('./src/components/getQRcode.vue')['default']
    Getweather: typeof import('./src/components/getweather.vue')['default']
    Goods: typeof import('./src/components/goods.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Map: typeof import('./src/components/map.vue')['default']
    Message: typeof import('./src/components/message.vue')['default']
    QRcode: typeof import('./src/components/QRcode.vue')['default']
  }
}
